// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: topigo.proto

package server

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateSubscriptionResponse_CreateSubscriptionResult int32

const (
	CreateSubscriptionResponse_Created CreateSubscriptionResponse_CreateSubscriptionResult = 0
	CreateSubscriptionResponse_Exists  CreateSubscriptionResponse_CreateSubscriptionResult = 1
)

// Enum value maps for CreateSubscriptionResponse_CreateSubscriptionResult.
var (
	CreateSubscriptionResponse_CreateSubscriptionResult_name = map[int32]string{
		0: "Created",
		1: "Exists",
	}
	CreateSubscriptionResponse_CreateSubscriptionResult_value = map[string]int32{
		"Created": 0,
		"Exists":  1,
	}
)

func (x CreateSubscriptionResponse_CreateSubscriptionResult) Enum() *CreateSubscriptionResponse_CreateSubscriptionResult {
	p := new(CreateSubscriptionResponse_CreateSubscriptionResult)
	*p = x
	return p
}

func (x CreateSubscriptionResponse_CreateSubscriptionResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateSubscriptionResponse_CreateSubscriptionResult) Descriptor() protoreflect.EnumDescriptor {
	return file_topigo_proto_enumTypes[0].Descriptor()
}

func (CreateSubscriptionResponse_CreateSubscriptionResult) Type() protoreflect.EnumType {
	return &file_topigo_proto_enumTypes[0]
}

func (x CreateSubscriptionResponse_CreateSubscriptionResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateSubscriptionResponse_CreateSubscriptionResult.Descriptor instead.
func (CreateSubscriptionResponse_CreateSubscriptionResult) EnumDescriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{1, 0}
}

type ModifySubscriptionResponse_ModifySubscriptionResult int32

const (
	ModifySubscriptionResponse_Success      ModifySubscriptionResponse_ModifySubscriptionResult = 0
	ModifySubscriptionResponse_DoesNotExist ModifySubscriptionResponse_ModifySubscriptionResult = 1
	ModifySubscriptionResponse_AlreadyInUse ModifySubscriptionResponse_ModifySubscriptionResult = 2
)

// Enum value maps for ModifySubscriptionResponse_ModifySubscriptionResult.
var (
	ModifySubscriptionResponse_ModifySubscriptionResult_name = map[int32]string{
		0: "Success",
		1: "DoesNotExist",
		2: "AlreadyInUse",
	}
	ModifySubscriptionResponse_ModifySubscriptionResult_value = map[string]int32{
		"Success":      0,
		"DoesNotExist": 1,
		"AlreadyInUse": 2,
	}
)

func (x ModifySubscriptionResponse_ModifySubscriptionResult) Enum() *ModifySubscriptionResponse_ModifySubscriptionResult {
	p := new(ModifySubscriptionResponse_ModifySubscriptionResult)
	*p = x
	return p
}

func (x ModifySubscriptionResponse_ModifySubscriptionResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModifySubscriptionResponse_ModifySubscriptionResult) Descriptor() protoreflect.EnumDescriptor {
	return file_topigo_proto_enumTypes[1].Descriptor()
}

func (ModifySubscriptionResponse_ModifySubscriptionResult) Type() protoreflect.EnumType {
	return &file_topigo_proto_enumTypes[1]
}

func (x ModifySubscriptionResponse_ModifySubscriptionResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModifySubscriptionResponse_ModifySubscriptionResult.Descriptor instead.
func (ModifySubscriptionResponse_ModifySubscriptionResult) EnumDescriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{3, 0}
}

type DeleteSubscriptionResponse_DeleteSubscriptionResult int32

const (
	DeleteSubscriptionResponse_Deleted DeleteSubscriptionResponse_DeleteSubscriptionResult = 0
	DeleteSubscriptionResponse_Error   DeleteSubscriptionResponse_DeleteSubscriptionResult = 1
)

// Enum value maps for DeleteSubscriptionResponse_DeleteSubscriptionResult.
var (
	DeleteSubscriptionResponse_DeleteSubscriptionResult_name = map[int32]string{
		0: "Deleted",
		1: "Error",
	}
	DeleteSubscriptionResponse_DeleteSubscriptionResult_value = map[string]int32{
		"Deleted": 0,
		"Error":   1,
	}
)

func (x DeleteSubscriptionResponse_DeleteSubscriptionResult) Enum() *DeleteSubscriptionResponse_DeleteSubscriptionResult {
	p := new(DeleteSubscriptionResponse_DeleteSubscriptionResult)
	*p = x
	return p
}

func (x DeleteSubscriptionResponse_DeleteSubscriptionResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteSubscriptionResponse_DeleteSubscriptionResult) Descriptor() protoreflect.EnumDescriptor {
	return file_topigo_proto_enumTypes[2].Descriptor()
}

func (DeleteSubscriptionResponse_DeleteSubscriptionResult) Type() protoreflect.EnumType {
	return &file_topigo_proto_enumTypes[2]
}

func (x DeleteSubscriptionResponse_DeleteSubscriptionResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteSubscriptionResponse_DeleteSubscriptionResult.Descriptor instead.
func (DeleteSubscriptionResponse_DeleteSubscriptionResult) EnumDescriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{5, 0}
}

type EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult int32

const (
	EndSubscriptionStreamingResponse_Ended EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult = 0
	EndSubscriptionStreamingResponse_Error EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult = 1
)

// Enum value maps for EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult.
var (
	EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult_name = map[int32]string{
		0: "Ended",
		1: "Error",
	}
	EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult_value = map[string]int32{
		"Ended": 0,
		"Error": 1,
	}
)

func (x EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult) Enum() *EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult {
	p := new(EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult)
	*p = x
	return p
}

func (x EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult) Descriptor() protoreflect.EnumDescriptor {
	return file_topigo_proto_enumTypes[3].Descriptor()
}

func (EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult) Type() protoreflect.EnumType {
	return &file_topigo_proto_enumTypes[3]
}

func (x EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult.Descriptor instead.
func (EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult) EnumDescriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{9, 0}
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionToken string `protobuf:"bytes,1,opt,name=subscriptionToken,proto3" json:"subscriptionToken,omitempty"`
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetSubscriptionToken() string {
	if x != nil {
		return x.SubscriptionToken
	}
	return ""
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result CreateSubscriptionResponse_CreateSubscriptionResult `protobuf:"varint,1,opt,name=result,proto3,enum=CreateSubscriptionResponse_CreateSubscriptionResult" json:"result,omitempty"`
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionResponse) GetResult() CreateSubscriptionResponse_CreateSubscriptionResult {
	if x != nil {
		return x.Result
	}
	return CreateSubscriptionResponse_Created
}

type ModifySubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionToken string   `protobuf:"bytes,1,opt,name=subscriptionToken,proto3" json:"subscriptionToken,omitempty"`
	Topics            []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
}

func (x *ModifySubscriptionRequest) Reset() {
	*x = ModifySubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySubscriptionRequest) ProtoMessage() {}

func (x *ModifySubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ModifySubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{2}
}

func (x *ModifySubscriptionRequest) GetSubscriptionToken() string {
	if x != nil {
		return x.SubscriptionToken
	}
	return ""
}

func (x *ModifySubscriptionRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type ModifySubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ModifySubscriptionResponse_ModifySubscriptionResult `protobuf:"varint,1,opt,name=result,proto3,enum=ModifySubscriptionResponse_ModifySubscriptionResult" json:"result,omitempty"`
}

func (x *ModifySubscriptionResponse) Reset() {
	*x = ModifySubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySubscriptionResponse) ProtoMessage() {}

func (x *ModifySubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySubscriptionResponse.ProtoReflect.Descriptor instead.
func (*ModifySubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{3}
}

func (x *ModifySubscriptionResponse) GetResult() ModifySubscriptionResponse_ModifySubscriptionResult {
	if x != nil {
		return x.Result
	}
	return ModifySubscriptionResponse_Success
}

type DeleteSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionToken string `protobuf:"bytes,1,opt,name=subscriptionToken,proto3" json:"subscriptionToken,omitempty"`
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSubscriptionRequest) GetSubscriptionToken() string {
	if x != nil {
		return x.SubscriptionToken
	}
	return ""
}

type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result DeleteSubscriptionResponse_DeleteSubscriptionResult `protobuf:"varint,1,opt,name=result,proto3,enum=DeleteSubscriptionResponse_DeleteSubscriptionResult" json:"result,omitempty"`
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSubscriptionResponse) GetResult() DeleteSubscriptionResponse_DeleteSubscriptionResult {
	if x != nil {
		return x.Result
	}
	return DeleteSubscriptionResponse_Deleted
}

type StartSubscriptionStreamingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionToken string `protobuf:"bytes,1,opt,name=subscriptionToken,proto3" json:"subscriptionToken,omitempty"`
}

func (x *StartSubscriptionStreamingRequest) Reset() {
	*x = StartSubscriptionStreamingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSubscriptionStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSubscriptionStreamingRequest) ProtoMessage() {}

func (x *StartSubscriptionStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSubscriptionStreamingRequest.ProtoReflect.Descriptor instead.
func (*StartSubscriptionStreamingRequest) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{6}
}

func (x *StartSubscriptionStreamingRequest) GetSubscriptionToken() string {
	if x != nil {
		return x.SubscriptionToken
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type EndSubscriptionStreamingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionToken string `protobuf:"bytes,1,opt,name=subscriptionToken,proto3" json:"subscriptionToken,omitempty"`
}

func (x *EndSubscriptionStreamingRequest) Reset() {
	*x = EndSubscriptionStreamingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndSubscriptionStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSubscriptionStreamingRequest) ProtoMessage() {}

func (x *EndSubscriptionStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSubscriptionStreamingRequest.ProtoReflect.Descriptor instead.
func (*EndSubscriptionStreamingRequest) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{8}
}

func (x *EndSubscriptionStreamingRequest) GetSubscriptionToken() string {
	if x != nil {
		return x.SubscriptionToken
	}
	return ""
}

type EndSubscriptionStreamingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult `protobuf:"varint,1,opt,name=result,proto3,enum=EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult" json:"result,omitempty"`
}

func (x *EndSubscriptionStreamingResponse) Reset() {
	*x = EndSubscriptionStreamingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndSubscriptionStreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSubscriptionStreamingResponse) ProtoMessage() {}

func (x *EndSubscriptionStreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSubscriptionStreamingResponse.ProtoReflect.Descriptor instead.
func (*EndSubscriptionStreamingResponse) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{9}
}

func (x *EndSubscriptionStreamingResponse) GetResult() EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult {
	if x != nil {
		return x.Result
	}
	return EndSubscriptionStreamingResponse_Ended
}

type PublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionToken string   `protobuf:"bytes,1,opt,name=subscriptionToken,proto3" json:"subscriptionToken,omitempty"`
	Message           *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{10}
}

func (x *PublishRequest) GetSubscriptionToken() string {
	if x != nil {
		return x.SubscriptionToken
	}
	return ""
}

func (x *PublishRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topigo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topigo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_topigo_proto_rawDescGZIP(), []int{11}
}

var File_topigo_proto protoreflect.FileDescriptor

var file_topigo_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x6f, 0x70, 0x69, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49,
	0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x9f, 0x01, 0x0a, 0x1a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x33, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x10, 0x01, 0x22, 0x61, 0x0a, 0x19, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x22, 0xb7,
	0x01, 0x0a, 0x1a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4b, 0x0a, 0x18, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x6f, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x49, 0x6e, 0x55, 0x73, 0x65, 0x10, 0x02, 0x22, 0x49, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x9e, 0x01, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x34, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x32, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x10, 0x01, 0x22, 0x51, 0x0a, 0x21, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x39, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x4f, 0x0a, 0x1f, 0x45, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0xb4, 0x01, 0x0a, 0x20, 0x45, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x40, 0x2e, 0x45, 0x6e, 0x64, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x64, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x36, 0x0a, 0x1e, 0x45, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x62, 0x0a, 0x0e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x11,
	0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xd2, 0x03, 0x0a, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x67, 0x6f, 0x12, 0x4d, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x1a, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x30, 0x01, 0x12, 0x5f, 0x0a, 0x18, 0x45, 0x6e, 0x64, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x45, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x45, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x12, 0x0f, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_topigo_proto_rawDescOnce sync.Once
	file_topigo_proto_rawDescData = file_topigo_proto_rawDesc
)

func file_topigo_proto_rawDescGZIP() []byte {
	file_topigo_proto_rawDescOnce.Do(func() {
		file_topigo_proto_rawDescData = protoimpl.X.CompressGZIP(file_topigo_proto_rawDescData)
	})
	return file_topigo_proto_rawDescData
}

var file_topigo_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_topigo_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_topigo_proto_goTypes = []interface{}{
	(CreateSubscriptionResponse_CreateSubscriptionResult)(0),             // 0: CreateSubscriptionResponse.CreateSubscriptionResult
	(ModifySubscriptionResponse_ModifySubscriptionResult)(0),             // 1: ModifySubscriptionResponse.ModifySubscriptionResult
	(DeleteSubscriptionResponse_DeleteSubscriptionResult)(0),             // 2: DeleteSubscriptionResponse.DeleteSubscriptionResult
	(EndSubscriptionStreamingResponse_EndSubscriptionStreamingResult)(0), // 3: EndSubscriptionStreamingResponse.EndSubscriptionStreamingResult
	(*CreateSubscriptionRequest)(nil),                                    // 4: CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),                                   // 5: CreateSubscriptionResponse
	(*ModifySubscriptionRequest)(nil),                                    // 6: ModifySubscriptionRequest
	(*ModifySubscriptionResponse)(nil),                                   // 7: ModifySubscriptionResponse
	(*DeleteSubscriptionRequest)(nil),                                    // 8: DeleteSubscriptionRequest
	(*DeleteSubscriptionResponse)(nil),                                   // 9: DeleteSubscriptionResponse
	(*StartSubscriptionStreamingRequest)(nil),                            // 10: StartSubscriptionStreamingRequest
	(*Message)(nil),                          // 11: Message
	(*EndSubscriptionStreamingRequest)(nil),  // 12: EndSubscriptionStreamingRequest
	(*EndSubscriptionStreamingResponse)(nil), // 13: EndSubscriptionStreamingResponse
	(*PublishRequest)(nil),                   // 14: PublishRequest
	(*PublishResponse)(nil),                  // 15: PublishResponse
}
var file_topigo_proto_depIdxs = []int32{
	0,  // 0: CreateSubscriptionResponse.result:type_name -> CreateSubscriptionResponse.CreateSubscriptionResult
	1,  // 1: ModifySubscriptionResponse.result:type_name -> ModifySubscriptionResponse.ModifySubscriptionResult
	2,  // 2: DeleteSubscriptionResponse.result:type_name -> DeleteSubscriptionResponse.DeleteSubscriptionResult
	3,  // 3: EndSubscriptionStreamingResponse.result:type_name -> EndSubscriptionStreamingResponse.EndSubscriptionStreamingResult
	11, // 4: PublishRequest.message:type_name -> Message
	4,  // 5: Topigo.CreateSubscription:input_type -> CreateSubscriptionRequest
	6,  // 6: Topigo.ModifySubscription:input_type -> ModifySubscriptionRequest
	8,  // 7: Topigo.DeleteSubscription:input_type -> DeleteSubscriptionRequest
	10, // 8: Topigo.StartSubscriptionStreaming:input_type -> StartSubscriptionStreamingRequest
	12, // 9: Topigo.EndSubscriptionStreaming:input_type -> EndSubscriptionStreamingRequest
	14, // 10: Topigo.Publish:input_type -> PublishRequest
	5,  // 11: Topigo.CreateSubscription:output_type -> CreateSubscriptionResponse
	7,  // 12: Topigo.ModifySubscription:output_type -> ModifySubscriptionResponse
	9,  // 13: Topigo.DeleteSubscription:output_type -> DeleteSubscriptionResponse
	11, // 14: Topigo.StartSubscriptionStreaming:output_type -> Message
	13, // 15: Topigo.EndSubscriptionStreaming:output_type -> EndSubscriptionStreamingResponse
	15, // 16: Topigo.Publish:output_type -> PublishResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_topigo_proto_init() }
func file_topigo_proto_init() {
	if File_topigo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_topigo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSubscriptionStreamingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndSubscriptionStreamingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndSubscriptionStreamingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topigo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_topigo_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topigo_proto_goTypes,
		DependencyIndexes: file_topigo_proto_depIdxs,
		EnumInfos:         file_topigo_proto_enumTypes,
		MessageInfos:      file_topigo_proto_msgTypes,
	}.Build()
	File_topigo_proto = out.File
	file_topigo_proto_rawDesc = nil
	file_topigo_proto_goTypes = nil
	file_topigo_proto_depIdxs = nil
}
